Repository DexterHuang/CyberCodeOnline, pull requests merged in 2021-05, with the labels that each got.

#638 .
  contribution/lang/ru.json
Labels: Confirmation Needed

#637 Update pt.json
  contribution/lang/pt.json
Labels: Confirmation Needed

#639 update de.json
  contribution/lang/de.json
Labels: Confirmation Needed

#635 update italian translations
  contribution/lang/it.json
Labels: Confirmation Needed

#642 Update it.json
  contribution/lang/it.json
Labels: Confirmation Needed

#645 Update zh-CN.json
  contribution/lang/zh-CN.json
Labels: Confirmation Needed

#641 Update zh-TW.json
  contribution/lang/zh-TW.json
Labels: Confirmation Needed

#648 Update zh-CN.json
  contribution/lang/zh-CN.json
Labels: Confirmation Needed

#652 added translations
  contribution/lang/it.json
Labels: Confirmation Needed

#651 done
  contribution/lang/ru.json
Labels: Confirmation Needed

#650 Update pt.json
  contribution/lang/pt.json
Labels: Confirmation Needed

#657 New translations added
  contribution/lang/es.json
Labels: Confirmation Needed

#660 Update zh-CN.json
  contribution/lang/zh-CN.json
Labels: Confirmation Needed

#682 Update ru translation
  contribution/lang/ru.json
Labels: Confirmation Needed, Discussion Needed

#685 Update locations.md
  mobile-tutorial/locations.md
Labels: Confirmation Needed

#691 added more translations
  contribution/lang/it.json
Labels: Confirmation Needed

#804 Update th.json
  contribution/lang/th.json
Labels: Confirmation Needed

#686 Update fr.json on lines 1 to 500
  contribution/lang/fr.json
Labels: help wanted

#823 Added some translations to fr.json
  contribution/lang/fr.json
Labels: Confirmation Needed

#835 Update id.json
  contribution/lang/id.json
Labels: Confirmation Needed

#841 guide
  UpdateNote.md
Labels: Confirmation Needed
