Repository DexterHuang/CyberCodeOnline, pull requests merged in 2021-06, with the labels that each got.

#849 Update zh-CN.json
  contribution/lang/zh-CN.json
Labels: Confirmation Needed

#867 id.json
  contribution/lang/id.json
Labels: Confirmation Needed

#873 update pt.json
  contribution/lang/pt.json
Labels: bug

#870 Update words.json
  contribution/words.json
Labels: Discussion Needed

#864 Update en.json
  contribution/lang/en.json
Labels: Confirmation Needed
